additionalProperties: false
properties:
  class:
    enum:
    - SchemaDefRequirement
    type: string
  types:
    items:
      oneOf:
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeEnum
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSchema
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordArray
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
    type: array
required:
- types
type: object
