oneOf:
- description: 'Indicates that the data pushed to the standard error stream by the command
    will be redirected to this CWL output.

    Can be defined for only one output. If combined with ''stderr'' at the root of the
    CWL document, that definition

    will indicate the desired name of the output file where the error stream will be
    written to.  A random name will

    be applied for the file of this output unless otherwise specified.

    '
  enum:
    - stderr
  type: string
- properties:
    type:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdErrDefinition
  required:
    - type
  type: object

