additionalProperties: false
properties:
  pattern:
    $comment: Either an expression or the regex pattern directly.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
  required:
    oneOf:
    - type: boolean
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
required:
- pattern
type: object
