additionalProperties: false
properties:
  class:
    $comment: Not 'NetworkAccessRequirement'
    enum:
    - NetworkAccess
    type: string
  networkAccess:
    description: Indicate whether a process requires outgoing IPv4/IPv6 network access.
    example: true
    oneOf:
      - type: boolean
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
    title: NetworkAccess
required:
- networkAccess
title: NetworkAccessRequirement
type: object
