additionalProperties: false
properties:
  class:
    $comment: Not 'NetworkAccessRequirement'
    enum:
    - NetworkAccess
    type: string
  networkAccess:
    $ref: bblocks://ogc.cwl.v1_2_1.NetworkAccess
required:
- networkAccess
title: NetworkAccessRequirement
type: object
