additionalProperties:
  $ref: bblocks://ogc.cwl.v1_2_1.UnknownRequirement
properties:
  BuiltinRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.BuiltinRequirement
  OGCAPIRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.OGCAPIRequirement
  WPS1Requirement:
    $ref: bblocks://ogc.cwl.v1_2_1.WPS1Requirement
type: object
