$comment: 'Identifier with text pattern that can allow additional non-ASCII characters
  depending on regex implementation.

  The identifier allows a ''#'' or a relative ''sub/part#ref'' prefix, to support
  references to other definitions

  in the CWL document, such as when using ''SchemaDefRequirement''.


  JSON spec regex does not include ''\w'' in its default subset to allow all word-like
  unicode characters

  (see reference: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html).


  Since support is implementation specific, add both the ASCII-only and ''\w'' representation
  simultaneously

  and let the parser reading this document apply whichever is more relevant or supported

  (see discussion: https://github.com/common-workflow-language/cwl-v1.2/pull/256#discussion_r1234037814).

  '
description: Generic identifier name pattern.
pattern: ^([A-Za-z0-9\w]+(/[A-Za-z0-9\w]+)*)?[#.]?[A-Za-z0-9\w]+(?:[-_.][A-Za-z0-9\w]+)*$
type: string
