$comment: Avoid 'oneOf' conflict of valid strings between this CWL record reference
  and the generic CWL types.
allOf:
- not:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeDefinition
- not:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLInputStdInDefinition
- not:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdOutDefinition
- not:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdErrDefinition
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordRefPattern
description: 'An IRI with minimally a ''{Record}'' identifier to look for a schema
  definition locally or remotely.


  The identifier resolution is performed accordingly to the specified reference and
  as described in

  https://www.commonwl.org/v1.2/SchemaSalad.html#Identifier_resolution.

  '
