description: Mapping of Workflow step inputs to nested CWL tool definitions inputs
  or outputs.
$defs:
  CWLWorkflowStepInMap:
    additionalProperties:
      oneOf:
        - type: string
        - items:
            type: string
          type: array
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepInput
    type: object
  CWLWorkflowStepInList:
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepInItem
    type: array

oneOf:
- $ref: '#/$defs/CWLWorkflowStepInMap'
- $ref: '#/$defs/CWLWorkflowStepInList'
