description: Mapping of Workflow step inputs to nested CWL tool definitions inputs
  or outputs.
items:
  oneOf:
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLIdentifier
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepOutId
type: array
