allOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLVersion
- $ref: bblocks://ogc.cwl.v1_2_1.CWLMetadata
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDocumentation
- $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowClass
- $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowBase
