# A short, descriptive name of this building block collection
name: Common Workflow Language building blocks

# Short abstract for this collection (optional)
abstract: |
  Common Workflow Language (CWL) is an open standard for describing how to run command line tools and connect them to create workflows.

# Description for this collection (optional)
description: |
  Tools and workflows described using CWL are portable across a variety of platforms that support the CWL standards. 
  Using CWL, it is easy to scale complex data analysis and machine learning workflows from a single
  developer's laptop up to massively parallel cluster, cloud and high performance computing environments.
  
  More information at [the Common Workflow Language website](https://www.commonwl.org/).

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.cwl.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore