description: 'Maximum reserved filesystem based storage for the designated temporary
  directory in mebibytes (2**20).

  See ''tmpdirMin'' for discussion about fractional storage requests.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Maximum reserved filesystem based storage for the designated temporary directory
  in mebibytes.
title: ResourceTmpDirMaximum
