properties:
  format:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLFormat
  loadContents:
    type: boolean
  secondaryFiles:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSecondaryFiles
  streamable:
    type: boolean
type: object
