description: "The compute capability supported by the GPU hardware.\n\n* If this is\
  \ a single value, it defines only the minimum compute capability.\n  GPUs with higher\
  \ capability are also accepted.\n* If it is an array value, then only select GPUs\
  \ with compute capabilities that explicitly\n  appear in the array.\n  See https://docs.nvidia.com/deploy/cuda-compatibility/#faq\
  \ and\n  https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#cuda-compute-capability\n\
  \  for details.\n"
oneOf:
- description: The compute capability supported by the GPU hardware.
  pattern: ^\d+\.\d+$
  title: CUDA compute capability
  type: string
- $ref: bblocks://ogc.cwl.v1_2_1.CUDAComputeCapabilityArray
title: CUDA compute capability
