additionalProperties: {}
properties:
  symbols:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeSymbols
  type:
    enum:
    - enum
    example: enum
    title: type
    type: string
required:
- type
- symbols
summary: CWL type as enum of values.
title: CWLTypeEnum
type: object
