description: 'The time limit, in seconds.


  A time limit of zero means no time limit.

  Negative time limits are an error.

  '
oneOf:
- minimum: 0.0
  type: number
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
title: TimeLimitValue
