additionalProperties: false
properties:
  class:
    enum:
    - SoftwareRequirement
    type: string
  packages:
    oneOf:
    - items:
        $ref: bblocks://ogc.cwl.v1_2_1.SoftwarePackage
      type: array
    - additionalProperties:
        oneOf:
        - $ref: bblocks://ogc.cwl.v1_2_1.SoftwarePackageSpecs
        - $ref: bblocks://ogc.cwl.v1_2_1.SoftwarePackage
      description: Mapping of 'package' name to its specifications.
      type: object
required:
- packages
type: object
