$defs:
  CWLWorkflowStepMap:
    additionalProperties:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepObject
    type: object
  CWLWorkflowStepList:
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepItem
    type: array
properties:
  hints:
    $comment: Technically a different subset, but lots of redefinitions to be done.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLHints
  inputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLInputsDefinition
  outputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputsDefinition
  requirements:
    $comment: Technically a different subset, but lots of redefinitions to be done.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirements
  steps:
    oneOf:
      - $ref: '#/$defs/CWLWorkflowStepMap'
      - $ref: '#/$defs/CWLWorkflowStepList'
type: object
