properties:
  hints:
    $comment: Technically a different subset, but lots of redefinitions to be done.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLHints
  inputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLInputsDefinition
  outputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputsDefinition
  requirements:
    $comment: Technically a different subset, but lots of redefinitions to be done.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirements
  steps:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowSteps
type: object
