description: 'Maximum reserved number of CPU cores.

  See ''coresMin'' for discussion about fractional CPU requests.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Maximum reserved number of CPU cores.
title: ResourceCoresMaximum
