oneOf:
- $comment: Either an expression or the regex pattern directly.
  $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSecondaryFileSchema
- items:
    $comment: Either an expression or the regex pattern directly.
    $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
  type: array
- items:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSecondaryFileSchema
  type: array
