oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeDefinition
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeArray
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeEnum
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordRef
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSchema
title: CWLTypeBase
