$defs:
  CWLTypeArray:
    additionalProperties: { }
    properties:
      items:
        $ref: bblocks://ogc.cwl.v1_2_1.CWLType
      type:
        enum:
          - array
        example: array
        title: type
        type: string
    required:
      - type
      - items
    summary: CWL type as list of items.
    title: CWLTypeArray
    type: object

oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeDefinition
- $ref: '#/$defs/CWLTypeArray'
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeEnum
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordRef
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeRecordSchema
title: CWLTypeBase
