description: 'Additional code fragments that will also be inserted before executing
  the expression code.

  Allows for function definitions that may be called from CWL expressions.

  '
items:
  $ref: bblocks://ogc.cwl.v1_2_1.InlineJavascriptLibItem
  title: exp_lib
title: InlineJavascriptLibraries
type: array
