additionalProperties: {}
description: Defines how to retrieve the output result from the command.
properties:
  glob:
    description: Glob pattern to find the output on disk or mounted docker volume.
    oneOf:
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
    - items:
        $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
      type: array
title: OutputBinding
type: object
