additionalProperties: false
description: 'Specify basic hardware resource requirements

  (see also: https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement).

  '
properties:
  class:
    enum:
    - ResourceRequirement
    type: string
  coresMax:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceCoresMaximum
  coresMin:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceCoresMinimum
  outdirMax:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceOutDirMaximum
  outdirMin:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceOutDirMinimum
  ramMax:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceRAMMaximum
  ramMin:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceRAMMinimum
  tmpdirMax:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceTmpDirMaximum
  tmpdirMin:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceTmpDirMinimum
title: ResourceRequirement
type: object
