additionalProperties: {}
properties:
  outputBinding:
    $ref: bblocks://ogc.cwl.v1_2_1.OutputBinding
  type:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLType
required:
- type
summary: CWL type definition with parameters.
title: CWLOutputObject
type: object
