description: 'Command called in the docker image or on shell according to requirements

  and hints specifications. Can be omitted if already defined in the docker

  image.

  '
oneOf:
- title: String command.
  type: string
- additionalProperties: false
  items:
    title: cmd
    type: string
  title: Command Parts
  type: array

title: CWLCommand
