description: 'Command called in the docker image or on shell according to requirements

  and hints specifications. Can be omitted if already defined in the docker

  image.

  '
oneOf:
- title: String command.
  type: string
- $ref: bblocks://ogc.cwl.v1_2_1.CommandParts
title: CWLCommand
