oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.BuiltinRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.OGCAPIRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.WPS1Requirement
- $ref: bblocks://ogc.cwl.v1_2_1.UnknownRequirement
