additionalProperties: false
properties:
  package:
    type: string
  specs:
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.ReferenceURL
    type: array
  version:
    items:
      type: string
    type: array
required:
- package
type: object
