properties:
  s:keywords:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLKeywordList
  version:
    description: Version of the process.
    example: 1.2.3
    pattern: ^\d+(\.\d+(\.\d+(\.[A-Za-z0-9\-_]+)*)*)*$
    title: version
    type: string
type: object
