properties:
  in:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepIn
  out:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepOut
  run:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepRun
  when:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepWhen
required:
- in
- run
- out
type: object
