allOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLInputObjectBase
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDefaultTypedConditional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDocumentation
summary: CWL type definition with parameters.
title: CWLInputObject
