additionalProperties: {}
properties:
  inputBinding:
    $ref: bblocks://ogc.cwl.v1_2_1.InputBinding
    additionalProperties: {}
  type:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLType
required:
- type
type: object
