$comment: 'The schema validation of the CWL will not itself perform the ''$import''
  to resolve and validate its contents.

  Therefore, the complete schema will not be validated entirely, and could still be
  partially malformed.

  To ensure proper and exhaustive validation of a CWL definition with this schema,
  all ''$import'' directives

  should be resolved and extended beforehand.

  '
additionalProperties: false
description: 'Represents an ''$import'' directive that should point toward another
  compatible CWL file to import where specified.

  The contents of the imported file should be relevant contextually where it is being
  imported.

  '
properties:
  $import:
    type: string
required:
- $import
type: object
