$comment: Avoid 'oneOf' conflict of valid strings between this CWL record reference
  and the generic CWL types.
allOf:
- not:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLTypeDefinition
- not:
    enum:
    - stdin
    type: string
- not:
    enum:
    - stdout
    type: string
- not:
    enum:
    - stderr
    type: string
- $ref: bblocks://ogc.cwl.v1_2_1.type-system.CWLTypeRecordRefPattern
description: 'An IRI with minimally a ''{Record}'' identifier to look for a schema
  definition locally or remotely.


  The identifier resolution is performed accordingly to the specified reference and
  as described in

  https://www.commonwl.org/v1.2/SchemaSalad.html#Identifier_resolution.

  '
