description: Explicit requirement to execute the application package.
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirementsMap
- $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirementsList
title: CWLRequirements
