additionalProperties: false
description: 'For implementations that support reusing output from past work

  (on the assumption that same code and same input produce same results),

  control whether to enable or disable the reuse behavior for a particular tool

  or step (to accommodate situations where that assumption is incorrect).


  A reused step is not executed but instead returns the same output as the original
  execution.


  If ''WorkReuse'' is not specified, correct tools should assume it is enabled by
  default.

  '
properties:
  class:
    $comment: Not 'WorkReuseRequirement'.
    enum:
    - WorkReuse
    type: string
  enableReuse:
    description: 'Indicates if reuse is enabled for this tool.


      Can be an expression when combined with ''InlineJavascriptRequirement''

      (see also: https://www.commonwl.org/v1.2/CommandLineTool.html#Expression).

      '
    oneOf:
      - type: boolean
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
    title: EnableReuseValue
required:
- enableReuse
title: WorkReuseRequirement
type: object
