$defs:
  EnvironmentDef:
    additionalProperties: false
    properties:
      envName:
        minLength: 1
        type: string
      envValue:
        $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
    required:
      - envName
      - envValue
    type: object
additionalProperties: false
properties:
  class:
    enum:
    - EnvVarRequirement
    type: string
  envDef:
    oneOf:
    - items:
        $ref: '#/$defs/EnvironmentDef'
      type: array
    - additionalProperties:
        oneOf:
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
          description: The 'envValue' specified directly
        - $ref: '#/$defs/EnvironmentDef'
      description: Mapping of 'envName' to environment value or definition.
      type: object
required:
- envDef
type: object
