anyOf:
- description: Unique identifier.
  format: uuid
  pattern: ^[a-f0-9]{8}(?:-?[a-f0-9]{4}){3}-?[a-f0-9]{12}$
  title: UUID
  type: string
- $ref: bblocks://ogc.cwl.v1_2_1.CWLTextPatternID
description: Reference to the process identifier.
title: CWLIdentifier
