description: All outputs produced by the Application Package.
$defs:
  CWLOutputList:
    description: Package outputs defined as items.
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputItem
    title: CWLOutputList
    type: array
  CWLOutputMap:
    additionalProperties:
      oneOf:
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLType
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputObject
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdOut
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdErr
        - $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
    description: Package outputs defined as mapping.
    properties: { }
    required: [ ]
    title: CWLOutputMap
    type: object

oneOf:
- $ref: '#/$defs/CWLOutputList'
- $comment: Avoid 'oneOf' conflict of generic mapping key strings as output identifier
    matching against '$import'.
  allOf:
  - $ref: '#/$defs/CWLOutputMap'
  - not:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
- $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
title: CWLOutputsDefinition
