description: Graph definition that defines *exactly one* CWL application package represented
  as list. Multiple definitions simultaneously deployed is NOT supported currently.
items:
  $ref: bblocks://ogc.cwl.v1_2_1.CWLGraphItem
maxItems: 1
minItems: 1
title: CWLGraphList
type: array
