description: 'Describes how to decompose the scattered input into a discrete

  set of jobs. When ''dotproduct'', specifies that each of the input arrays

  are aligned and one element taken from each array to construct each job.

  It is an error if all input arrays are of different length. When ''nested_crossproduct'',

  specifies the Cartesian product of the inputs, producing a job for every

  combination of the scattered inputs. The output must be nested arrays

  for each level of scattering, in the order that the input arrays are listed

  in the scatter field. When ''flat_crossproduct'', specifies the Cartesian

  product of the inputs, producing a job for every combination of the scattered

  inputs. The output arrays must be flattened to a single level, but otherwise

  listed in the order that the input arrays are listed in the scatter field.

  '
enum:
- dotproduct
- nested_crossproduct
- flat_crossproduct
title: scatterMethod
type: string
