additionalProperties: false
properties:
  DockerRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.DockerRequirement
  EnvVarRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.EnvVarRequirement
  InitialWorkDirRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.InitialWorkDirRequirement
  InlineJavascriptRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.InlineJavascriptRequirement
  InplaceUpdateRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.InplaceUpdateRequirement
  LoadListingRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.LoadListingRequirement
  MultipleInputFeatureRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.MultipleInputFeatureRequirement
  NetworkAccess:
    $comment: Not 'NetworkAccessRequirement'
    $ref: bblocks://ogc.cwl.v1_2_1.NetworkAccessRequirement
  ResourceRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.ResourceRequirement
  ScatterFeatureRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.ScatterFeatureRequirement
  SchemaDefRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.SchemaDefRequirement
  ShellCommandRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.ShellCommandRequirement
  SoftwareRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.SoftwareRequirement
  StepInputExpressionRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.StepInputExpressionRequirement
  SubworkflowFeatureRequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.SubworkflowFeatureRequirement
  ToolTimeLimit:
    $comment: Not 'ToolTimeLimitRequirement'.
    $ref: bblocks://ogc.cwl.v1_2_1.ToolTimeLimitRequirement
  WorkReuse:
    $comment: Not 'WorkReuseRequirement'.
    $ref: bblocks://ogc.cwl.v1_2_1.WorkReuseRequirement
  cwltool:CUDARequirement:
    $ref: bblocks://ogc.cwl.v1_2_1.cwltool:CUDARequirement
title: CWLRequirementsMap
type: object
