default: 256
description: 'Minimum reserved RAM in mebibytes (2**20).


  May be a fractional value. If so, the actual RAM request must be rounded up

  to the next whole number.


  The reported amount of RAM reserved for the process, which is available to

  expressions on the ''CommandLineTool'' as ''runtime.ram'', must be a non-zero integer.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Minimum reserved RAM in mebibytes.
title: ResourceRAMMinimum
