additionalProperties: false
properties:
  checksum:
    $ref: bblocks://ogc.cwl.v1_2_1.Checksum
  class:
    enum:
    - File
    - Directory
    type: string
  location:
    type: string
  size:
    minimum: 0
    type: integer
required:
- class
- location
type: object
