additionalProperties:
  oneOf:
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLType
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLInputObject
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLInputStdIn
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
description: Package inputs defined as mapping.
properties: {}
required: []
title: CWLInputMap
type: object
