additionalProperties:
  oneOf:
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLType
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputObject
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdOut
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputStdErr
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
description: Package outputs defined as mapping.
properties: {}
required: []
title: CWLOutputMap
type: object
