additionalProperties: false
properties:
  class:
    enum:
    - InitialWorkDirRequirement
    type: string
  listing:
    $ref: bblocks://ogc.cwl.v1_2_1.InitialWorkDirListing
required:
- listing
title: InitialWorkDirRequirement
type: object
