$defs:
  InitialWorkDirListing:
    oneOf:
      - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
      - items:
          oneOf:
            - type: 'null'
            - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
            - $ref: bblocks://ogc.cwl.v1_2_1.DirectoryListingDirent
            - $ref: bblocks://ogc.cwl.v1_2_1.DirectoryListingFileOrDirectory
            - items:
                $ref: bblocks://ogc.cwl.v1_2_1.DirectoryListingFileOrDirectory
              type: array
        title: InitialWorkDirListingItems
        type: array
    title: InitialWorkDirListing

additionalProperties: false
properties:
  class:
    enum:
    - InitialWorkDirRequirement
    type: string
  listing:
    $ref: '#/$defs/InitialWorkDirListing'
required:
- listing
title: InitialWorkDirRequirement
type: object
