$comment: 'For any new items added, ensure they are added under ''class'' of ''UnknownRequirement''
  as well.

  Otherwise, insufficiently restrictive classes could cause multiple matches, failing
  the ''oneOf'' condition.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.cwltool:CUDARequirement
- $ref: bblocks://ogc.cwl.v1_2_1.DockerRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.SoftwareRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.ShellCommandRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.EnvVarRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.SchemaDefRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.InitialWorkDirRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.InlineJavascriptRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.InplaceUpdateRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.LoadListingRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.NetworkAccessRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.ScatterFeatureRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.ToolTimeLimitRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.WorkReuseRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.MultipleInputFeatureRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.StepInputExpressionRequirement
- $ref: bblocks://ogc.cwl.v1_2_1.SubworkflowFeatureRequirement
title: CWLRequirementsItem
