$comment: Called 'Dirent' in documentation.
additionalProperties: false
properties:
  entry:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
  entryname:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
  writable:
    type: boolean
required:
- entry
title: DirectoryListingDirent
type: object
