$defs:
  CWLWorkflowStepMap:
    additionalProperties:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepObject
    type: object
  CWLWorkflowStepList:
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.CWLWorkflowStepItem
    type: array
oneOf:
- $ref: '#/$defs/CWLWorkflowStepMap'
- $ref: '#/$defs/CWLWorkflowStepList'
