description: 'Indicates that the value passed to this CWL input will be redirected
  to the standard input stream of the command.

  Can be defined for only one input and must not be combined with ''stdin'' at the
  root of the CWL document.

  '
enum:
- stdin
type: string
