$defs:
  AnyLiteralList:
    items:
      $ref: bblocks://ogc.cwl.v1_2_1.AnyLiteralType
    title: AnyLiteralList
    type: array
description: Default value of input if not provided for task execution.
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.AnyLiteralType
- $ref: '#/$defs/AnyLiteralList'
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDefaultLocation
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDefaultObject
- items:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLDefaultObject
  type: array
title: CWLDefault
