$comment: 'For any new items added, ensure they are added under ''class'' of ''UnknownRequirement''
  as well.

  Otherwise, insufficiently restrictive classes could cause multiple matches, failing
  the ''oneOf'' condition.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirementsItem
- $ref: bblocks://ogc.cwl.v1_2_1.CWLHintsItemExtras
title: CWLHintsItem
