description: 'Maximum reserved RAM in mebibytes (2**20).

  See ''ramMin'' for discussion about fractional RAM requests.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Maximum reserved RAM in mebibytes.
title: ResourceRAMMaximum
