$comment: 'Whenever this option is applicable for a parameter, any other ''normal''
  string should not be specified.

  For JSON schema validation, there is no easy way to distinguish them unless using
  complicated string patterns.

  '
description: 'When combined with ''InlineJavascriptRequirement'', this field allows
  runtime parameter references

  (see also: https://www.commonwl.org/v1.2/CommandLineTool.html#Expression).

  '
title: CWLExpression
type: string
