additionalProperties: false
description: 'Specify the desired behavior for loading the listing field of a ''Directory''
  object for use by expressions

  (see also: https://www.commonwl.org/v1.2/CommandLineTool.html#LoadListingRequirement).

  '
properties:
  class:
    enum:
    - LoadListingRequirement
    type: string
  loadListing:
    $ref: bblocks://ogc.cwl.v1_2_1.LoadListingEnum
required:
- loadListing
title: LoadListingRequirement
type: object
