$comment: 'CWL ''type'' is not specified at this level for step inputs

  (it is provided by the mapped input of the nested tool instead).

  Therefore, cannot validate against ''CWLDefaultTypedConditional''.

  '
properties:
  default:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLDefault
type: object
