allOf:
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDefaultTypedConditional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLDocumentation
additionalProperties: {}
description: 'Input specification. Note that multiple formats are supported and

  not all specification variants or parameters are presented here. Please refer

  to official CWL documentation for more details (https://www.commonwl.org).

  '
properties:
  id:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLIdentifier
    description: Identifier of the CWL input.
  inputBinding:
    $ref: bblocks://ogc.cwl.v1_2_1.InputBinding
  type:
    oneOf:
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLType
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLInputStdIn
required:
- type
- id
title: Input
type: object
