additionalProperties: {}
properties:
  arguments:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLArguments
  baseCommand:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLCommand
  class:
    description: CWL class specification. This is used to differentiate between single
      Application Package (AP)definitions and Workflow that chains multiple packages.
    enum:
    - CommandLineTool
    - ExpressionTool
    - Workflow
    title: Class
    type: string
  hints:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLHints
  id:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLIdentifier
  inputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLInputsDefinition
  intent:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLIntent
  outputs:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLOutputsDefinition
  requirements:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLRequirements
  scatter:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLScatter
  scatterMethod:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLScatterMethod
required:
- class
- id
- inputs
- outputs
title: CWLGraphItem
type: object
