additionalProperties: {}
properties:
  id:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLIdentifier
    description: Identifier of the CWL input.
  inputBinding:
    $ref: bblocks://ogc.cwl.v1_2_1.InputBinding
  type:
    oneOf:
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLType
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLInputStdIn
required:
- type
- id
type: object
