additionalProperties: false
oneOf:
- required:
  - dockerPull
- required:
  - dockerImport
- required:
  - dockerLoad
- required:
  - dockerFile
properties:
  class:
    enum:
    - DockerRequirement
    type: string
  dockerFile:
    type: string
  dockerImageId:
    type: string
  dockerImport:
    type: string
  dockerLoad:
    type: string
  dockerOutputDirectory:
    type: string
  dockerPull:
    description: Reference package that will be retrieved and executed by CWL.
    example: docker-registry.host.com/namespace/image:1.2.3
    title: Docker pull reference
    type: string
title: DockerRequirement
type: object
