default: 1024
description: 'Minimum reserved filesystem based storage for the designated output

  directory in mebibytes (2**20).


  May be a fractional value. If so, the actual storage request must be rounded

  up to the next whole number.


  The reported amount of storage reserved for the process, which is available

  to expressions on the ''CommandLineTool'' as ''runtime.outdirSize'', must be a non-zero
  integer.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Minimum reserved filesystem based storage for the designated output directory
  in mebibytes.
title: ResourceOutDirMinimum
