default: 1
description: 'Maximum reserved filesystem based storage for the designated output

  directory in mebibytes (2**20).

  See ''outdirMin'' for discussion about fractional storage requests.

  '
oneOf:
- $ref: bblocks://ogc.cwl.v1_2_1.ResourceQuantityOrFractional
- $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
summary: Maximum reserved filesystem based storage for the designated output directory
  in mebibytes.
title: ResourceOutDirMaximum
