additionalProperties: false
description: Defines how to specify the input for the command.
properties:
  itemSeparator:
    type: string
  position:
    oneOf:
    - type: integer
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
  prefix:
    type: string
  shellQuote:
    type: boolean
  valueFrom:
    $ref: bblocks://ogc.cwl.v1_2_1.CWLExpression
title: Input Binding
type: object
